import PDFDocument from "pdfkit";

export const drawPharmacyBillInfo = (doc:any, bill: any) => {
  const y = doc.y;

  doc
    .font("Helvetica-Bold")
    .fontSize(14)
    .fillColor("#1E3A8A")
    .text("PHARMACY BILL", 40, y);

  doc.moveDown(0.5);

  const boxY = doc.y;

  doc.roundedRect(40, boxY, 515, 105, 8).fillAndStroke("#F8FAFC", "#D1D5DB");

  doc.fillColor("black").font("Helvetica").fontSize(10);

  doc.text("Bill Number", 60, boxY + 15);
  doc.text(bill.billNumber, 170, boxY + 15);

  doc.text("Invoice Date", 60, boxY + 35);
  doc.text(new Date(bill.createdAt).toLocaleString(), 170, boxY + 35);

  doc.text("Payment Status", 60, boxY + 55);

  doc
    .fillColor(bill.paymentStatus === "PAID" ? "#16A34A" : "#DC2626")
    .font("Helvetica-Bold")
    .text(bill.paymentStatus, 170, boxY + 55);

  // Right Side

  doc.fillColor("black").font("Helvetica");

  doc.text("Patient", 330, boxY + 15);
  doc.text(bill.patientName, 420, boxY + 15);

  doc.text("Total", 330, boxY + 35);

  doc
    .font("Helvetica-Bold")
    .fillColor("#2563EB")
    .text(`₹${bill.totalAmount.toFixed(2)}`, 420, boxY + 35);

  doc.text("Generated By", 330, boxY + 55);

  doc
    .fillColor("black")
    .font("Helvetica")
    .text(bill.cashier ?? "Reception", 420, boxY + 55);

  doc.y = boxY + 110;
};
