import PDFDocument from "pdfkit";

export const drawPharmacyPatientCard = (
  doc: any,
  bill: any
) => {
  doc
    .font("Helvetica-Bold")
    .fontSize(14)
    .fillColor("#1E3A8A")
    .text("PATIENT INFORMATION");

  doc.moveDown(0.5);

  const y = doc.y;

  doc
    .roundedRect(40, y, 515, 105, 8)
    .fillAndStroke("#FFFFFF", "#D1D5DB");

  doc
    .fillColor("black")
    .font("Helvetica")
    .fontSize(10);

  // Left Column
  doc.text("Patient Name", 60, y + 15);
  doc.text(bill.patientName, 170, y + 15);

  doc.text("Bill Number", 60, y + 35);
  doc.text(bill.billNumber, 170, y + 35);

  doc.text("Invoice Date", 60, y + 55);
  doc.text(
    new Date(bill.createdAt).toLocaleDateString(),
    170,
    y + 55
  );

  // Right Column
  doc.text("Payment Status", 330, y + 15);

  doc
    .fillColor(
      bill.paymentStatus === "PAID"
        ? "#16A34A"
        : "#DC2626"
    )
    .font("Helvetica-Bold")
    .text(
      bill.paymentStatus,
      450,
      y + 15
    );

  doc
    .fillColor("black")
    .font("Helvetica");

  doc.text("Total Amount", 330, y + 35);

  doc
    .font("Helvetica-Bold")
    .fillColor("#2563EB")
    .text(
      `₹${bill.totalAmount.toFixed(2)}`,
      450,
      y + 35
    );

  doc
    .fillColor("black")
    .font("Helvetica");

  doc.text("Generated By", 330, y + 55);

  doc.text(
    bill.cashier ?? "Reception",
    450,
    y + 55
  );

  doc.y = y + 110;
};