ALTER TABLE "PharmacyBill"
ADD COLUMN IF NOT EXISTS "cashier" TEXT,
ADD COLUMN IF NOT EXISTS "discount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "dueAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "gstAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "paidAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "paymentStatus" TEXT NOT NULL DEFAULT 'PAID',
ADD COLUMN IF NOT EXISTS "pharmacist" TEXT,
ADD COLUMN IF NOT EXISTS "subtotal" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "PharmacyBillItem"
ADD COLUMN IF NOT EXISTS "batchNumber" TEXT,
ADD COLUMN IF NOT EXISTS "gst" DOUBLE PRECISION NOT NULL DEFAULT 0;